language: ruby
rvm:
- 2.2.9
- 2.3.4
- 2.4.3
- 2.5.0
- jruby-9.1.14.0
before_install:
- pip install --upgrade --user awscli
- gem update --system
- gem install bundler
before_script:
- mysql -e 'create database thinking_sphinx;' > /dev/null
- psql -c 'create database thinking_sphinx;' -U postgres >/dev/null
- "./bin/loadsphinx $SPHINX_VERSION"
- bundle exec appraisal install
script: bundle exec appraisal rspec
env:
  global:
  - SPHINX_BIN=ext/sphinx/bin/
  - secure: cUPinkilBafqDSPsTkl/PXYc2aXNKUQKXGK8poBBMqKN9/wjfJx1DWgtowDKalekdZELxDhc85Ye3bL1xlW4nLjOu+U6Tkt8eNw2Nhs1flodHzA/RyENdBLr/tBHt43EjkrDehZx5sBHmWQY4miHs8AJz0oKO9Ae2inTOHx9Iuc=
  matrix:
  - DATABASE=mysql2 SPHINX_VERSION=2.0.10
  - DATABASE=postgresql SPHINX_VERSION=2.0.10
  - DATABASE=mysql2 SPHINX_VERSION=2.1.9
  - DATABASE=postgresql SPHINX_VERSION=2.1.9
  - DATABASE=mysql2 SPHINX_VERSION=2.2.11
  - DATABASE=postgresql SPHINX_VERSION=2.2.11
sudo: false
addons:
  postgresql: '9.4'
services:
- postgresql
matrix:
  exclude:
  - rvm: jruby-9.1.14.0
    env: DATABASE=mysql2 SPHINX_VERSION=2.0.10
  - rvm: jruby-9.1.14.0
    env: DATABASE=postgresql SPHINX_VERSION=2.0.10
