highligher: rouge
name: Thinking Sphinx
url: https://freelancing-gods.com/thinking-sphinx
author:
  name: Pat Allan
  uri: https://freelancing-gods.com/about.html
exclude:
  - bin
  - Gemfile
  - Gemfile.lock
  - gemfiles
  - pkg
  - vendor
  - spec
plugins:
  - jekyll-redirect-from
